apiVersion: v1
kind: Service
metadata:
  name: nfs-server-2
spec:
  # clusterIP: 10.85.4.174
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-2