apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.7.250
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3000Gi