apiVersion: batch/v1
kind: Job
metadata:
  name: job-karan
spec:
  template:
    spec:
      containers:
        - command:
            - sleep 
            - "60"
          image: 291343978134.dkr.ecr.us-west-2.amazonaws.com/aws-tf2-torch:latest
          name: job-karan
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: efs-pvc
              mountPath: /home
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs-1
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
      nodeSelector:
#        k8s.amazonaws.com/accelerator: nvidia-tesla-v100 # or nvidia-tesla-p100 or nvidia-tesla-p4 or nvidia-tesla-v100 or nvidia-tesla-t4
        kops.k8s.io/instancegroup: v100-1
#      tolerations:
#        - key: "gpu_num"
#          operator: "Equal"
#          value: "1"
#          effect: "NoSchedule"