apiVersion: v1
kind: Pod
metadata:
  name: pod-karan
  labels:
    app: app
spec:
  containers:
    - command:
        - sleep
        - infinity
      image: 291343978134.dkr.ecr.us-west-2.amazonaws.com/aws-tf2-torch:latest
      name: pod-karan
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: efs-pvc
          mountPath: /home
        - name: dshm
          mountPath: /dev/shm
      ports:
        - name: jupyter
          containerPort: 8000
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs-1
    - name: dshm
      emptyDir:
        medium: Memory
  restartPolicy: Never
  # nodeSelector:
  #   # Make sure that your cluster actually has the accelerator you're requesting!
  #   accelerator: nvidia-tesla-t4 # or nvidia-tesla-p100 or nvidia-tesla-p4 or nvidia-tesla-v100 or nvidia-tesla-t4