kind: Service
apiVersion: v1
metadata:
  name: streamlit
spec:
  selector:
    # kops.k8s.io/instancegroup: nodes #
    app: app

  # Make the service externally visible via the node
  type: NodePort

  ports:
    # Which port on the node is the service available through?
    - nodePort: 30001

    # Inside the cluster, what port does the service expose?
      port: 8001

    # Which port do pods selected by this service expose?
      targetPort: 8001
