kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
  namespace: default
spec:
  selector:
      matchLabels:
          app: efs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccount: efs-provisioner
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              value: fs-490549e3
            - name: AWS_REGION
              value: us-west-2
            - name: DNS_NAME
              value: ""
            - name: PROVISIONER_NAME
              value: efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-490549e3.efs.us-west-2.amazonaws.com
            path: /
